services:
  traefik:
    image: traefik:v3.2.1
    # start with docker-compose up -d and let be alive
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      # for the local admin UI
      - "8181:8181"
    extra_hosts:
      # needed for routers/services provided from files
      # MUST match the IP used for the created network
      - "host.docker.internal:host-gateway"
    logging:
      options:
        max-size: "1m"
    volumes:
      # a directory where dynamic file configs can be placed
      - ./dynamic:/etc/traefik/sites.d
      # dev certs
      - ./local-certs:/etc/traefik/certs
      # The Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # For resolver cert storage
      - ./letsencrypt:/letsencrypt
    stop_signal: SIGINT
    command:
      - "--api"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.forwardedheaders.trustedips=127.0.0.1/32"
      - "--entrypoints.traefik.address=:8181"
      - "--log.level=ERROR"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.directory=/etc/traefik/sites.d/"

networks:
  default:
    name: localdevelopment
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${LOCAL_NETWORK_IP:-172.21.0.0}/24
