services:
  traefik:
    image: traefik:v2.9
    # start with docker-compose up -d and let be alive
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8181:8181"
    extra_hosts:
      # needed for routers/services provided from files
      # MUST match the IP used for the created network
      - "host.docker.internal:host-gateway"
    logging:
      options:
        max-size: "1m"
    volumes:
      # the traefik static config
      - ./traefik.yml:/etc/traefik/traefik.yml
      # a directory where dynamic file configs can be placed
      - ./dynamic:/etc/traefik/sites.d
      # dev certs
      - ./local-certs:/etc/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: localdevelopment
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${LOCAL_NETWORK_IP}/24
