version: '3'

services:
  traefik:
    image: traefik:v2.4
    # start with docker-compose up -d and let be alive
    restart: unless-stopped
    ports:
      - "80:80"
      - "8181:8181"
    extra_hosts:
      # needed for routers/services provided from files
      # MUST match the IP used for the created network
      - "host.docker.internal:172.21.0.1"
    volumes:
      # the traefik static config
      - ./traefik.yml:/etc/traefik/traefik.yml
      # a directory where dynamic file configs can be placed
      - ./dynamic:/etc/traefik/sites.d
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: bridge
    name: localdevelopment
    ipam:
      config:
      - gateway: 172.21.0.1
      - subnet: 172.21.0.0/24
