api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: :80
  https:
    address: :443
  traefik:
    address: :8181

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    watch: true
    directory: "/etc/traefik/sites.d/"

log:
  level: ERROR

accessLog: {}

docker:
  domain: local
  watch: true
