api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: :80
  https:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
  traefik:
    address: :8181

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    watch: true
    directory: "/etc/traefik/sites.d/"

log:
  level: ERROR

accessLog: {}
